Add test for ssh: py implementation

diff --git a/test/15sync_via_ssh b/test/15sync_via_ssh
--- a/test/15sync_via_ssh
+++ b/test/15sync_via_ssh
@@ -2,10 +2,12 @@ if [ "$SSH_TEST_ENABLED" == "1" ]; then
 
 trap "lvremove -f $VG/__lvmsynctest_src || true;
       lvremove -f $VG/__lvmsynctest_dest || true;
+      lvremove -f $VG/__lvmsynctest_destpy || true;
       lvremove -f $VG/__lvmsynctest_snap || true" EXIT
 
 lvcreate -l 5 -n __lvmsynctest_src $VG
 lvcreate -l 5 -n __lvmsynctest_dest $VG
+lvcreate -l 5 -n __lvmsynctest_destpy $VG
 
 # Fill src with gibberish
 dd if=/dev/urandom of=/dev/$VG/__lvmsynctest_src bs=1M || true
@@ -27,20 +29,27 @@ done
 
 # Now lvmsync with ssh
 lvmsync /dev/$VG/__lvmsynctest_snap localhost:/dev/$VG/__lvmsynctest_dest  || true
+lvmsync.py /dev/$VG/__lvmsynctest_snap localhost:/dev/$VG/__lvmsynctest_destpy  || true
 
 # Verify that our source and dest are now equal
 SRCSUM="$(md5sum </dev/$VG/__lvmsynctest_src)"
 DESTSUM="$(md5sum </dev/$VG/__lvmsynctest_dest)"
+DESTSUMPY="$(md5sum </dev/$VG/__lvmsynctest_destpy)"
 
 # Cleanup
 lvremove -f $VG/__lvmsynctest_snap
 lvremove -f $VG/__lvmsynctest_dest
+lvremove -f $VG/__lvmsynctest_destpy
 lvremove -f $VG/__lvmsynctest_src
 
 
 trap "" EXIT
 
 # Make sure test succeeded
+if [ "$DESTSUMPY" != "$DESTSUM" ]; then
+	echo "FAIL: 15sync_via_ssh: implementation mismatch"
+	exit 1
+fi
 if [ "$SRCSUM" != "$DESTSUM" ]; then
 	echo "FAIL: 15sync_via_ssh"
 	exit 1
