Add python test for reverse netcat: needs SSH_TEST_ENABLED=1 to run

diff --git a/test/25sync_via_reversenetcat b/test/25sync_via_reversenetcat
--- a/test/25sync_via_reversenetcat
+++ b/test/25sync_via_reversenetcat
@@ -1,10 +1,12 @@
 if [ "$SSH_TEST_ENABLED" == "1" ]; then
 trap "lvremove -f $VG/__lvmsynctest_src || true;
       lvremove -f $VG/__lvmsynctest_dest || true;
+      lvremove -f $VG/__lvmsynctest_destpy || true;
       lvremove -f $VG/__lvmsynctest_snap || true" EXIT
 
 lvcreate -l 5 -n __lvmsynctest_src $VG
 lvcreate -l 5 -n __lvmsynctest_dest $VG
+lvcreate -l 5 -n __lvmsynctest_destpy $VG
 
 # Fill src with gibberish
 dd if=/dev/urandom of=/dev/$VG/__lvmsynctest_src bs=1M || true
@@ -14,6 +16,7 @@ lvcreate --snapshot $VG/__lvmsynctest_src -l 5 -n __lvmsynctest_snap
 
 # Initial copy
 dd if=/dev/$VG/__lvmsynctest_src of=/dev/$VG/__lvmsynctest_dest bs=1M
+dd if=/dev/$VG/__lvmsynctest_src of=/dev/$VG/__lvmsynctest_destpy bs=1M
 
 # Write in some gibberish at intervals across the LV
 i=0
@@ -23,6 +26,7 @@ done
 
 # Now lvmsync -- reverse netcat the diff over the wire
 lvmsync -N localhost:56125 /dev/$VG/__lvmsynctest_snap localhost:/dev/$VG/__lvmsynctest_dest  || true
+lvmsync.py -N localhost:56126 /dev/$VG/__lvmsynctest_snap localhost:/dev/$VG/__lvmsynctest_destpy || true
 
 # Verify that our source and dest are now equal
 SRCSUM="$(md5sum </dev/$VG/__lvmsynctest_src)"
@@ -32,11 +36,16 @@ DESTSUMPY="$(md5sum </dev/$VG/__lvmsynctest_destpy)"
 # Cleanup
 lvremove -f $VG/__lvmsynctest_snap
 lvremove -f $VG/__lvmsynctest_dest
+lvremove -f $VG/__lvmsynctest_destpy
 lvremove -f $VG/__lvmsynctest_src
 
 trap "" EXIT
 
 # Make sure test succeeded
+if [ "$DESTSUMPY" != "$DESTSUM" ]; then
+	echo "FAIL: 25sync_via_reversenetcat: implementation mismatch"
+	exit 1
+fi
 if [ "$SRCSUM" != "$DESTSUM" ]; then
 	echo "FAIL: 25sync_via_reversenetcat"
 	exit 1
